### PR TITLE
[move][logger] Move `logger.py` to `sparseml.core`

### PR DESCRIPTION
**Pull request by rahul-tuli**
This PR migrates existing logger framework to `sparseml.core`

Main Changes:

- [X] Move `src/sparseml/pytorch/utils/logger.py` --> `src/sparseml/core/logger.py` + update `__init__.py` files
- [X] Update usages
- [X] Move Tests

Also asserted that imports work just fine:
```python
$ python                                                                                                   (migrate-existing-logger-framework|✚1⚑2)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sparseml.pytorch.sparsification import LayerPruningModifier
>>> from sparseml.pytorch.utils import log_sparsification_info
>>> from sparseml.pytorch.optim import RecipeManagerStepWrapper
>>> 
```

Note: Updated import logic to include loggers in `sparseml/pytorch/utils/__init__.py` all above import verified to still work as expected

### CODE REVIEW

File: src/sparseml/core/logger.py [hunk 1]
```diff
@@ -578,7 +579,7 @@ def __init__(
 
         if os.environ.get("NM_TEST_MODE"):
             test_log_path = os.environ.get("NM_TEST_LOG_DIR")
-            create_dirs(test_log_path)
+            _create_dirs(test_log_path)
```
Comment (dsikka) [inline src/sparseml/core/logger.py:582]: what happened to the original `create_dirs` function? Is it still be used elsewhere?

**Review by dsikka — APPROVED** [review]
LGTM pending tests

**Comment by Satrat** [comment]
Looks like there is failing integration test, but otherwise looks fine to me!
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/bin/sparseml.yolov5.export_onnx", line 5, in <module>
    from sparseml.yolov5.scripts import export
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sparseml/yolov5/scripts.py", line 17, in <module>
    from yolov5.export import export_run
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/yolov5/export.py", line 76, in <module>
    from yolov5.utils.neuralmagic import apply_recipe_one_shot, export_sample_inputs_outputs, neuralmagic_onnx_export
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/yolov5/utils/neuralmagic/__init__.py", line 1, in <module>
    from .sparsification_manager import *
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/yolov5/utils/neuralmagic/sparsification_manager.py", line 7, in <module>
    from sparseml.pytorch.utils import SparsificationGroupLogger
ImportError: cannot import name 'SparsificationGroupLogger' from 'sparseml.pytorch.utils' (/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sparseml/pytorch/utils/__init__.py)
tests/integrations/yolov5/test_yolov5.py E
```

**Comment by rahul-tuli** [comment]
The failing test should be fixed after https://github.com/neuralmagic/yolov5/pull/240

File: src/sparseml/pytorch/utils/__init__.py [hunk 2]
```diff
@@ -18,13 +18,13 @@
 
 # flake8: noqa
 
+from ...core.logger import *
```
Comment (bfineran) [inline src/sparseml/pytorch/utils/__init__.py:21]: instead of importing from `.core` here, let's still keep `src/sparseml/utils/logger.py` and have it import from core.loggers and add the relevant classes to the `__all__` list, and then add a note that it's been moved

Comment (rahul-tuli) [reply src/sparseml/pytorch/utils/__init__.py]: Done!

**Review by bfineran — APPROVED** [review]

**Review by dbogunowicz — APPROVED** [review]
