### ISSUE TITLE
Loading quantized `efficientnet_vs_s` via ModelRegistry leads to AttributeError: 'Conv2d' object has not attribute 'module'

### ISSUE THREAD

**Issue by clementpoiret** [neuralmagic/sparseml#1405]
**Describe the bug**
I want to transfer your already-optimized EffNet v2 model from SparseZoo. My architecture is a bit different from the built-in `_Classifier` so I am forced to use a more conventional pathway than your CLI. To do so, I call `sparseml.pytorch.models.ModelRegistry`.
Loading the "base" pretrained model works well, but when `pretrained="base_quant-none"`, I get the issue: `AttributeError: 'Conv2d' object has not attribute 'module'`

**Expected behavior**

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Arch Linux
2. Python version [e.g. 3.7]: 3.9
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: 1.4.0
4. ML framework version(s) [e.g. torch 1.7.1]: Pytorch 1.12.1; Lightning 1.9.0
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]: SparseZoo 1.4.0
6. Other relevant environment information [e.g. hardware, CUDA version]:

**To Reproduce**
Exact steps to reproduce the behavior:

Here is a demo code :

```python
import pytorch_lightning as pl
import torch
from sparseml.pytorch.models import ModelRegistry
from torch import nn

registry = ModelRegistry()


class Regressor(nn.Module):

    def __init__(self, n_predictions: int, dropout_rate: float = 0.2):
        super().__init__()
        self.regressor = nn.Sequential(
            nn.Conv2d(256, 1280, kernel_size=1, bias=False),
            nn.SiLU(),
            nn.AdaptiveAvgPool2d(1),
            nn.Dropout(dropout_rate),
            nn.Flatten(),
            nn.Linear(1280, n_predictions),
        )

    def forward(self, x):
        x = self.regressor(x)

        # Normally, the backbone returns a tuple of (x, x).
        # As returning only x causes an error when calling the backbone,
        # we return a tuple of (x, dummy) instead.
        return x, torch.tensor(0)


class LightningModel(pl.LightningModule):

    def __init__(
        self,
        n_predictions: int,
        dropout_rate: float = 0.2,
        model_name: str = "efficientnet_v2_s",
        pretrained: bool = True,
        lr: float = 5e-4,
    ):
        super().__init__()

        self.lr = lr

        self.backbone = registry.create(model_name, pretrained=pretrained)

        # Classifier is: conv -> bn -> SiLU -> pool -> dropout -> fc
        self.backbone.classifier = Regressor(n_predictions, dropout_rate)

        self.loss = nn.MSELoss()

    def forward(self, x):
        x = self.backbone(x)[0]

        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = self.loss(y_hat, y)
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = self.loss(y_hat, y)
        self.log("val_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
        return optimizer


if __name__ == "__main__":
    dummy = torch.rand(1, 3, 224, 224)

    # This works fine
    model = LightningModel(22, model_name="efficientnet_v2_s", pretrained=True)
    print(model)
    y_hat = model(dummy)

    # This causes an error
    model = LightningModel(
        22,
        model_name="efficientnet_v2_s",
        pretrained="base_quant-none",
    )
    print(model)
    y_hat = model(dummy)
```

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

```
>>> registry.create(model_name, pretrained="base_quant-none", ignore_error_tensors=["Conv2d"])
Traceback (most recent call last):
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/models/registry.py", line 375, in wrapper
    load_model(path, model, load_strict, ignore)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/utils/model.py", line 132, in load_model
    thin_model_from_checkpoint(model, model_dict)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/utils/helpers.py", line 1017, in thin_model_from_checkpoint
    layer = get_layer(layer_name, model)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/utils/helpers.py", line 717, in get_layer
    layer = layer.__getattr__(name)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/models/registry.py", line 119, in create
    model = ModelRegistry._CONSTRUCTORS[key_copy](
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/models/registry.py", line 379, in wrapper
    load_model(path, model, load_strict, ignore)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/utils/model.py", line 132, in load_model
    thin_model_from_checkpoint(model, model_dict)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/utils/helpers.py", line 1017, in thin_model_from_checkpoint
    layer = get_layer(layer_name, model)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/sparseml/pytorch/utils/helpers.py", line 717, in get_layer
    layer = layer.__getattr__(name)
  File "/home/cp264607/anaconda3/envs/***/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'module'
```

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by bfineran** [comment]
Hi @clementpoiret I was able to reproduce your error on sparseml 1.4.  However I was able to verify the `registry.create` command works with sparseml 1.5.  The latest quantized efficientnet models were developed with a few additions for quantization added in sparseml 1.5 development.

Could you switch to sparseml-nightly to get these changes? You could also use a dev install (`pip install -e .` from a clone).

**Comment by clementpoiret** [comment]
Dear @bfineran, you're right, it works well using sparseml 1.5.
Thanks for your answer!
